# Generated by Django 5.2.4 on 2025-09-18 04:35

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSeason',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Marks the record as deleted without removing it.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Stores additional metadata in JSON format.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('name', models.CharField(help_text='Name of the season (e.g., Fall 2025, Spring 2026).', max_length=100, unique=True)),
                ('academic_year', models.CharField(help_text='Academic year for the season (e.g., 2025/2026).', max_length=20)),
                ('start_date', models.DateField(help_text='Start date for applications.')),
                ('end_date', models.DateField(help_text='End date for applications.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this season is currently active.')),
            ],
            options={
                'verbose_name': 'Admission Season',
                'verbose_name_plural': 'Admission Seasons',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='euadmissionapplication',
            name='season',
            field=models.ForeignKey(help_text='Admission season for this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_applications', to='admission.admissionseason'),
        ),
        migrations.AddField(
            model_name='noneuadmissionapplication',
            name='season',
            field=models.ForeignKey(help_text='Admission season for this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_applications', to='admission.admissionseason'),
        ),
    ]
