# Generated by Django 5.2.4 on 2025-09-17 00:03

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noneuadmissionapplication',
            name='diploma_city_country',
        ),
        migrations.RemoveField(
            model_name='noneuadmissionapplication',
            name='diploma_details',
        ),
        migrations.RemoveField(
            model_name='noneuadmissionapplication',
            name='diploma_institution',
        ),
        migrations.RemoveField(
            model_name='noneuadmissionapplication',
            name='diploma_year',
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Marks the record as deleted without removing it.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Stores additional metadata in JSON format.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address associated with the record creation or update.', null=True)),
                ('name', models.CharField(help_text='Name of the diploma obtained or in progress, including mention if applicable.', max_length=200)),
                ('institution', models.CharField(help_text='Institution where the diploma was obtained or is in progress.', max_length=200)),
                ('city_country', models.CharField(help_text='City and country of the institution.', max_length=200)),
                ('year', models.CharField(help_text='Year the diploma was obtained or expected.', max_length=4)),
                ('user', models.ForeignKey(help_text='User who obtained or is pursuing this diploma.', on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diploma',
                'verbose_name_plural': 'Diplomas',
            },
        ),
        migrations.AddField(
            model_name='euadmissionapplication',
            name='diplomas',
            field=models.ManyToManyField(help_text='Diplomas associated with this application.', related_name='%(class)s_applications', to='admission.diploma'),
        ),
        migrations.AddField(
            model_name='noneuadmissionapplication',
            name='diplomas',
            field=models.ManyToManyField(help_text='Diplomas associated with this application.', related_name='%(class)s_applications', to='admission.diploma'),
        ),
    ]
