# Generated by Django 5.2.4 on 2025-09-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_admissionseason_euadmissionapplication_season_and_more'),
        ('admission', '0002_remove_noneuadmissionapplication_diploma_city_country_and_more'),
    ]

    operations = [
    ]
