# Generated by Django 5.2.4 on 2025-09-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_merge_20250918_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='euadmissionapplication',
            name='address',
        ),
        migrations.RemoveField(
            model_name='euadmissionapplication',
            name='city',
        ),
        migrations.RemoveField(
            model_name='euadmissionapplication',
            name='country',
        ),
        migrations.RemoveField(
            model_name='euadmissionapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='euadmissionapplication',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='euadmissionapplication',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='euadmissionapplication',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='euadmissionapplication',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='noneuadmissionapplication',
            name='address',
        ),
        migrations.RemoveField(
            model_name='noneuadmissionapplication',
            name='city',
        ),
        migrations.RemoveField(
            model_name='noneuadmissionapplication',
            name='country',
        ),
        migrations.RemoveField(
            model_name='noneuadmissionapplication',
            name='email',
        ),
        migrations.RemoveField(
            model_name='noneuadmissionapplication',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='noneuadmissionapplication',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='noneuadmissionapplication',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='noneuadmissionapplication',
            name='postal_code',
        ),
    ]
