# Generated by Django 5.2.4 on 2025-09-18 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_remove_euadmissionapplication_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionseason',
            name='session_start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Start date of the academic session (e.g., 15 October 2025).'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admissionseason',
            name='name',
            field=models.CharField(help_text='Name of the season (e.g., October 2025, February 2026).', max_length=100, unique=True),
        ),
    ]
