# Generated by Django 5.2.4 on 2025-09-20 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_admissionseason_session_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='entry_level',
            field=models.CharField(choices=[('BAC', 'BAC'), ('BAC+2', 'BAC +2'), ('BAC+3', 'BAC +3'), ('BAC+4', 'BAC +4'), ('BAC+5', 'BAC +5')], default=django.utils.timezone.now, help_text='Entry level required for the program (e.g., BAC, BAC +2).', max_length=50),
            preserve_default=False,
        ),
    ]
